// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2d4hvzA2Yhh8ixvTvP3F38ZhoBMLPIxI',
    appId: '1:512467211027:web:f554821bebbdcae369c0e6',
    messagingSenderId: '512467211027',
    projectId: 'notely-8fe37',
    authDomain: 'notely-8fe37.firebaseapp.com',
    storageBucket: 'notely-8fe37.firebasestorage.app',
    measurementId: 'G-CNMQL4XYDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDz74PdeCnGua6a11XQUOM9viavk_2b-A',
    appId: '1:512467211027:android:e6ad4c537e6777a869c0e6',
    messagingSenderId: '512467211027',
    projectId: 'notely-8fe37',
    storageBucket: 'notely-8fe37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9LJExAZ1G-WrYBo1u4BdFWEKx8XqDWKs',
    appId: '1:512467211027:ios:66bb74fe84479d7069c0e6',
    messagingSenderId: '512467211027',
    projectId: 'notely-8fe37',
    storageBucket: 'notely-8fe37.firebasestorage.app',
    iosBundleId: 'com.hadi87s.notely',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9LJExAZ1G-WrYBo1u4BdFWEKx8XqDWKs',
    appId: '1:512467211027:ios:66bb74fe84479d7069c0e6',
    messagingSenderId: '512467211027',
    projectId: 'notely-8fe37',
    storageBucket: 'notely-8fe37.firebasestorage.app',
    iosBundleId: 'com.hadi87s.notely',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2d4hvzA2Yhh8ixvTvP3F38ZhoBMLPIxI',
    appId: '1:512467211027:web:c720447f8f87fd4469c0e6',
    messagingSenderId: '512467211027',
    projectId: 'notely-8fe37',
    authDomain: 'notely-8fe37.firebaseapp.com',
    storageBucket: 'notely-8fe37.firebasestorage.app',
    measurementId: 'G-DE3MTHSRX9',
  );
}
